# Generated by Django 4.0.4 on 2022-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bestseller',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
